Adapt gRPC example to work with Astra
stargate/stargate pull request #1292
Opened 2021-10-01 07:37 UTC by tomekl007

**What this PR does**:
Adapts the `GrpcClientExecuteQueryAstra` to allow user to interact with the gRPC API on the astra cluster (not only local `Staragate`)

**Checklist**
- [ ] Changes manually tested
- [ ] Documentation added/updated

2021-10-01 11:19 UTC, ivansenic approved these changes

2021-10-01 16:54 UTC, dougwettlaufer requested changes
We don't need something Astra specific here. As discussed offline let's handle this somewhere else.

2021-10-01 18:47 UTC, tomekl007 commented
> We don't need something Astra specific here. As discussed offline let's handle this somewhere else.

Could you elaborate more? Where is the `somewhere else`?

2021-10-04 15:54 UTC, tatu-at-datastax commented on grpc-examples/src/main/java/io/stargate/grpcexample/GrpcClientExecuteQuery.java
> +  private static final String STARGATE_HOST = "localhost";;
Super tiny but there's an extra semicolon :)

2021-11-02 08:39 UTC, closed without merging