First part of #1644: C*3 from 3.11.11->3.11.12
stargate/stargate pull request #1646
Opened 2022-02-16 23:32 UTC by tatu-at-datastax

**What this PR does**:

Starting work on #1644: first upgrade Cassandra-3: separate upgrades to isolate problems.

**Which issue(s) this PR fixes**:

Will eventually resolve #1644 but not with just this PR.

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated -- relies on test coverage
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2022-02-17 00:01 UTC, tatu-at-datastax commented
Alas, immediate (unit) test failures for seemingly trivial update:

```
Step #4 - "cassandra-3.11": [INFO] Running io.stargate.db.cassandra.Cassandra311PersistenceActivatorTest
Step #4 - "cassandra-3.11": [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.48 s - in io.stargate.db.cassandra.Cassandra311PersistenceActivatorTest
Step #4 - "cassandra-3.11": [INFO] 
Step #4 - "cassandra-3.11": [INFO] Results:
Step #4 - "cassandra-3.11": [INFO] 
Step #4 - "cassandra-3.11": [ERROR] Errors: 
Step #4 - "cassandra-3.11": [ERROR]   StargateQueryHandlerTest.authorizeByTokenBatchStatement:936 ? IllegalState Can...
Step #4 - "cassandra-3.11": [ERROR]   IdempotencyAnalyzerTest.shouldReturnIdempotentIfAllStatementsWithinABatchAreIdempotent:102 ? IllegalState
Step #4 - "cassandra-3.11": [ERROR]   IdempotencyAnalyzerTest.shouldReturnNonIdempotentIfAllStatementsWithinABatchAreNonIdempotent:117 ? IllegalState
Step #4 - "cassandra-3.11": [INFO] 
```

2022-02-17 08:44 UTC, ivansenic reviewed
Hey @tatu-at-datastax, can you please go through the list that I made with the last update -> https://github.com/stargate/stargate/tree/master/persistence-cassandra-3.11#cassandra-version-update and check all the points.. Could be that thrift version moved, and is not back in the transitive deps of the `3.11`..

Also the list is missing the docker files updates for the `v2`.. Maybe we can add a PR for the `v2` branch once everything is updated on the `master`.

2022-02-17 11:10 UTC, ivansenic requested changes
Stops from merging, due to the https://github.com/stargate/stargate/pull/1647#issuecomment-1042836170. Same issue exists in the `3.11.12` as well.

2022-02-17 11:54 UTC, ivansenic commented
The other failing tests here are reproducible locally..

```
Step #4 - "cassandra-3.11": [ERROR] Errors: 
Step #4 - "cassandra-3.11": [ERROR]   StargateQueryHandlerTest.authorizeByTokenBatchStatement:936 ? IllegalState Can...
Step #4 - "cassandra-3.11": [ERROR]   IdempotencyAnalyzerTest.shouldReturnIdempotentIfAllStatementsWithinABatchAreIdempotent:102 ? IllegalState
Step #4 - "cassandra-3.11": [ERROR]   IdempotencyAnalyzerTest.shouldReturnNonIdempotentIfAllStatementsWithinABatchAreNonIdempotent:117 ? IllegalState
```

Seems like a bug due to this changed line in [BatchStatement.Parsed](https://github.com/apache/cassandra/blame/cassandra-3.11.12/src/java/org/apache/cassandra/cql3/statements/BatchStatement.java#L568). The `isFullyQualified()` is called, which throws the `IllegalArgumentException` in the super class `CFStatement`. I don't really understand how can a batch be fully qualified, this has to be a bug.. This should be confirmed by the (BatchStatement.Parsed constructor)[https://github.com/apache/cassandra/blame/cassandra-3.11.12/src/java/org/apache/cassandra/cql3/statements/BatchStatement.java#L514-L520] that calls super with `null`.

This bug does not exist in the `4.0.2` as they correctly override the [isFullyQualified()](https://github.com/apache/cassandra/blame/cassandra-4.0.2/src/java/org/apache/cassandra/cql3/statements/BatchStatement.java#L613-L621) method.

2022-02-17 21:52 UTC, tatu-at-datastax commented
As per comment on parent issue, could be due to:

https://issues.apache.org/jira/browse/CASSANDRA-17248

2022-02-17 22:59 UTC, tatu-at-datastax commented
Completed work from update list, but as to the real problem(s), I am not quite sure how to proceed.

2022-02-23 09:32 UTC, ivansenic commented
Seems that calling `QueryProcessor.getStatement` instead of `QueryProcessor.parseStatement` does the trick and batches are correctly prepared in that case.. If tests are green, I will update all the tests existing in all persistence modules to not use `QueryProcessor.parseStatement`.. 

Seems we only use this in tests, so should be fine overall..

2022-02-23 16:20 UTC, ivansenic approved these changes
@tatu-at-datastax Approving, but please make sure race condition is fixed in #1647

2022-02-23 16:32 UTC, merged