Write tests
stargate/stargate pull request #1942
Opened 2022-07-01 23:10 UTC by EricBorczuk

**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2022-07-05 08:17 UTC, ivansenic commented
@EricBorczuk I am re-basing this in order to trigger the new CI..

2022-07-05 08:30 UTC, ivansenic approved these changes
Seems good, fix the comment and merge on green..

2022-07-05 08:30 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +    public void withTtl() {
should we also test for longer ttls that will not delete the document just after write

2022-07-05 08:30 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +  class WriteDocument {
missing cases:

* write to a collection that does not exist
* write empty object
* write non-empty array
* write empty array
* write primitive JSON
* write without body

2022-07-05 08:30 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +          .atLeast(0, TimeUnit.MILLISECONDS)
`atLeast` is not used correct here (https://github.com/awaitility/awaitility/wiki/Usage#at-least), actually has no affect.. Remove.. 

`atMost` with 2 seconds (1s ttl +1s buffer) seems like the correct way imo

2022-07-05 08:30 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +      assertThat(expectedIds).isEmpty();
all of this with:

```
.then()
.statusCode(202)
.body("documentIds", contains("1", "2", "3"))
```

2022-07-05 08:30 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +          .atLeast(0, TimeUnit.MILLISECONDS)
same as above

2022-07-06 10:03 UTC, ivansenic requested changes
Something is wrong, why is writing the empty object or empty array not allowed here? Do we have the bug here in V1 as well?

OK seems that this is V1 behavior as well, and it was like this since forever apparently as `POST` was using the `documentService#putAtPath`.. However, this seems extremely off to me, let's sync please..

2022-07-06 10:03 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +      Awaitility.await()
here the idea was to assert document is there after writting before ttl expires

2022-07-06 10:03 UTC, ivansenic commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +                  "Updating a key with just an empty object or an empty array is not allowed. Hint: update the parent path with a defined object instead."));
Same here?

2022-07-06 15:27 UTC, EricBorczuk commented on sgv2-docsapi/src/test/java/io/stargate/sgv2/docsapi/api/v2/namespaces/collections/documents/DocumentWriteResourceIntegrationTest.java
> +    }
Made a ticket for this (and empty array): https://datastax.jira.com/browse/C2-1899

2022-07-06 18:12 UTC, merged