V1/V2 Docs API compat test
stargate/stargate pull request #1990
Opened 2022-07-19 21:09 UTC by EricBorczuk

**What this PR does**:
Adds a small script that uses Docs API V1 to write documents and ensures that they can be retrieved and modified by V2.

**Which issue(s) this PR fixes**:

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2022-07-19 21:37 UTC, jeffreyscarpenter reviewed
This is an interesting check but won't we end up deleting it soon, since we'll soon be disabling Docs API in coordinator?

2022-07-20 14:49 UTC, EricBorczuk commented
It's really just meant as a one-off to make sure that right now, what we have in V2 is correct/compatible; since it's not integrated into CI or anything, it won't interfere with any code changes and also it is meant to be deleted once we remove the V1 docs API

2022-07-21 09:56 UTC, ivansenic requested changes
I like the approach very much, why not have this as code :)

The only thing I need is configurable hosts and ports for both V1 and V2.. On my setup the V1 would be `127.0.0.4:8083` and V2 `127.0.0.1:8180`.. You can make that configurable by system properties or main method arguments, both are fine with me.. Defaults can stay as is now..

Once you update I ll run the test..

2022-07-21 15:48 UTC, EricBorczuk commented
OK - should be able to configure using system properties now.

When you test locally, you'll have to create a keyspace manually called `test_namespace` before you run

2022-07-21 16:49 UTC, ivansenic approved these changes

2022-07-21 16:49 UTC, ivansenic commented on testing/src/main/java/io/stargate/it/http/docsapi/compatibility/DocumentsV1ToV2Compat.java
> +    authToken = RestUtils.getAuthToken(v2Host);
does not work, should be `v1Host`..

2022-07-21 16:49 UTC, ivansenic commented on testing/src/main/java/io/stargate/it/http/docsapi/compatibility/DocumentsV1ToV2Compat.java
> +  private static String namespace = "test_namespace";
could be parametrized as well..

2022-07-25 15:18 UTC, merged