disabe vert.x uri validation in the v2 docker images
stargate/stargate pull request #2138
Opened 2022-10-05 14:08 UTC by ivansenic

**What this PR does**:
The `-Dvertx.disableURIValidation=true` works and disables the URI validation, but can not be defined in the `application.yaml` config.. I had no other idea, then actually adding this to the docker image.. Or should we leave this as optional in the deployment?

Another thing I noticed in the docker images is `JAVA_OPTS` and `JAVA_OPTS_APPEND`. Would defining a `JAVA_OPTS` in the container during deployment actually overwrite what I added? We need to use the `JAVA_OPTS_APPEND` then..

It would be nice to have a test for this, will try to add one maybe.

**Tasks:**

* [ ] Test
* [ ] Final agreement on the option specification

2022-10-05 14:08 UTC, ivansenic commented
@EricBorczuk can you double check that this works? build a docker and fire a request
@tatu-at-datastax what do you think about this option?

2022-10-05 14:59 UTC, EricBorczuk approved these changes

2022-10-05 15:25 UTC, ivansenic commented
Need to add this to the native image profile as well

2022-10-05 16:33 UTC, tatu-at-datastax commented
@ivansenic So what is the problem this is needed to fix? Is that related to where clause issues Lorina noticed?

It is quite odd that it cannot be defined in `application.yaml`, but if so I guess this is the way to do it.
I wish it wasn't since it's both hidden and then  if running using other mechanisms (start with Maven, or `starctl` etc) need to add option for those separately. But I do not have any better ideas here.

2022-10-05 16:34 UTC, tatu-at-datastax commented
One thing I do note is this from https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/VertxHttpRecorder.java: 

```
        /** JVM system property that disables URI validation, don't use this in production. */
        private static final String DISABLE_URI_VALIDATION_PROP_NAME = "vertx.disableURIValidation";
```

so... do we really need and want to use this in production?

2022-10-06 09:54 UTC, ivansenic commented
> 

@tatu-at-datastax Let's sync on this please..

2022-10-06 17:19 UTC, tatu-at-datastax requested changes
I think I would like to discuss this first to make sure we really want to do it.
I am bit concerned that we would do this to support incorrect usage, allow violating expected escaping.
For example, I think our Postman collections use unescaped curly braces and brackets ({, }, [, ]): this is not legal usage, I think. But was allowed by Jersey in the past.

But I understand that it may be necessary, not so much wrt allowing wrong escaping but avoiding NPEs or 400s with no response. Just want to understand to trade-offs.

2022-10-12 00:05 UTC, tatu-at-datastax commented
Ok I think @ivansenic may have gone through it all but just in case I'll add what I found on client side, for Postman.

Looks like they do not want to encode anything but bare minimum of absolutely required characters; that's one way to look at things. So the problem we have has been reported as:

https://github.com/postmanlabs/postman-app-support/issues/8808

but closed as, I think, "wont fix unless there is a specific problem".

There is per-request configuration -- "Encode URL automatically" -- which can be disabled and manually encoding necessary characters (`=`, `{`, `}`) which we could use.
And then there is the question of what `curl` does wrt escaping, if anything.

2022-10-14 16:05 UTC, tatu-at-datastax commented
As per discussion, we do want to go with this approach. Changes look good but I need to build locally to validate this works.

2022-10-14 17:25 UTC, tatu-at-datastax commented
@ivansenic I tested this and confirmed that a `curl` like:

    curl -i --location --request GET 'localhost:8082/v2/keyspaces/baselines/iot/rows?where=\{\}' --header "X-Cassandra-Token: $AUTH_TOKEN"

* fails from docker image built from `v2.0.0` (with empty 400)
* passes URL validation with docker build from this PR (gives 400 for missing table i.e. hits REST API & persistence)

So I think it works as expected. I tested with C*4 backend should work the same for all.

2022-10-14 17:28 UTC, tatu-at-datastax approved these changes

2022-10-14 17:33 UTC, merged