Fix for C2-1835
stargate/stargate pull request #2307
Opened 2022-12-15 13:47 UTC by versaurabh

**What this PR does**:

Enforces guardrail checks by Stargate for Astra classic & AD4D

- via making Stargate pass the actual username to the backend DSE for Astra classic and AD4D clusters
- the backend DSE for Astra classic & AD4D clusters use `AstraAuthenticator` which own Authn/z for the the actual username identified by the token (via https://github.com/riptano/cloud-ondemand/pull/4186)

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2022-12-19 19:21 UTC, jeffreyscarpenter commented
looks like CI failures on this PR are causes by formatting errors, which you can correct by running 

`mvn com.coveo:fmt-maven-plugin:format`

2022-12-20 09:12 UTC, ivansenic requested changes
Is this backward compatible change? I see this as a very good change and I am all :+1: for it, but I am afraid if this is actually work in the clusters that already exist? Are we certain that all the client names in the tokens are actually having a correct user in the DB (with all permissions needed).

Also I am not sure if this is actually dismissing the concept of the `TRANSITIONAL_AUTH`? Maybe a safer solution would be here to do something like:

```
 if (user.isFromExternalAuth()) {
   if (USE_TRANSITIONAL_AUTH) {
         loginSingle = this.clientState.login(EXTERNAL_AUTH_USER);
   } else {
         loginSingle = this.clientState.login(new ExternalAuthenticatedUser(user.name()));
   }
}
```

But then this can cause the different deployment configs, so could be even more confusing in a way..

@jeffreyscarpenter wdyt?

I am marking with *Request changes* until we figure it out..

2022-12-20 20:37 UTC, jeffreyscarpenter commented
@kathirsvn might have better perspective to comment on Ivan's concerns?

2022-12-21 11:23 UTC, versaurabh commented
> the client names in the tokens are actually having a correct

hi @ivansenic AFAIK, each token is guaranteed to be present in the OPA backend alongwith the permissions info over there. 
For Astra instance, the DSE authn/z is uses OPA backend via https://github.com/riptano/dse-astra-auth-lib/

2023-02-03 14:26 UTC, jeffreyscarpenter commented
@kathirsvn can you take a look at this and recommend next step?

2023-08-03 23:36 UTC, closed without merging