Hazel/add grpc vector test
stargate/stargate pull request #2722
Opened 2023-08-09 17:06 UTC by Hazel-Datastax

**What this PR does**:
Added vector type codec to stargate grpc.
Add unit test for vector support in grpc。

**Which issue(s) this PR fixes**:
Fixes #2654

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2023-08-09 17:17 UTC, maheshrajamani requested changes
Since this is for grpc api exposed to users, can you add some integration tests?
Current grpc integration tests can be found in this folder[here](https://github.com/stargate/stargate/tree/main/coordinator/testing/src/main/java/io/stargate/it/grpc)?

2023-08-09 17:35 UTC, Hazel-Datastax commented
Yes, I am still working on it. Thank you for mentioning it.

2023-08-09 19:57 UTC, maheshrajamani commented
> Yes, I am still working on it. Thank you for mentioning it.

Ah I didn't see the PR in draft.

2023-08-17 19:19 UTC, maheshrajamani requested changes

2023-08-17 19:19 UTC, maheshrajamani commented on coordinator/testing/src/main/java/io/stargate/it/grpc/VectorQueryTest.java
> +  public void insertAndGet(@TestKeyspace CqlIdentifier keyspace) {
Can you also add some test for insert and select cases with binding variables? Similar to examples [here](https://github.com/stargate/stargate/blob/bab9b5c19dc586959f95fa170392082ef8e3e833/coordinator/testing/src/main/java/io/stargate/it/grpc/ExecuteQueryTest.java#L72C5-L79C38)

2023-08-18 00:26 UTC, Yuqi-Du commented
Need to change the size unmatched message.
[related](https://github.com/stargate/stargate/pull/2726/files)

2023-08-18 18:22 UTC, maheshrajamani approved these changes
LGTM.

2023-08-18 20:52 UTC, merged